# Generated by Django 5.2.1 on 2025-06-10 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='favorite_genres',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='favorite_platforms',
            field=models.TextField(blank=True),
        ),
    ]
