# Generated by Django 5.2.1 on 2025-06-15 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_userprofile_favorite_genres_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='game',
            field=models.ForeignKey(db_column='game_id', on_delete=django.db.models.deletion.CASCADE, to='main.game', to_field='game_id'),
        ),
        migrations.AlterField(
            model_name='gamerating',
            name='game',
            field=models.ForeignKey(db_column='game_id', on_delete=django.db.models.deletion.CASCADE, to='main.game', to_field='game_id'),
        ),
    ]
